name: com.example.aa
description: A Flutter project using the Stacked architecture, featuring internationalization, multiple flavors, and various utility classes. The app is a simple counter application that increments the counter by 2 with each button click.
version: 1.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.1.10
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  generate: true