name: com.example.aa
description: A Flutter project using the Stacked architecture, featuring internationalization, multiple flavors, and various utility classes. The app is a simple counter application where the counter increments by 2 with each button click.
version: 1.0.0
environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.1.10
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  stacked_generator: ^1.3.3
  mockito: ^5.4.1

flutter:
  uses-material-design: true
  generate: true